name: client
description: "SABRINE PFE"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get_it: ^7.6.7
  get: ^4.6.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  http: ^1.2.1
  google_maps_flutter: ^2.6.0
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0
  flutter_screenutil: ^5.9.0
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.0
  permission_handler: ^10.2.0
  path_provider: ^2.0.13
  multi_image_picker_view: ^0.0.15
  image_cropper: ^5.0.1
  image_picker: ^1.1.0
  animated_bottom_navigation_bar: ^1.3.3
  flutter_svg: ^2.0.5
  dotted_border: ^2.0.0+3
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  intl: ^0.19.0
  shimmer: ^3.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
#  fonts:
#    - family: Times
#      fonts:
#        - asset: fonts/Poppins/times new roman.ttf
#          weight: 300
#        - asset: fonts/Times/times new roman bold.ttf
#          weight: 800




